name: vue-front-build-push

# 1. 이벤트 트리거(on)
on: 
    push:
        branches: 
            - main

# 2. Jobs - runner 설치
jobs: 
    build-and-push:
        runs-on: ubuntu-latest
# 3. source checkout
        steps:
            - name: Source Checkout
              uses: actions/checkout@v2

# 4. setup node
            - name: Setup node
              uses: actions/checkout@v2

# 5. docker buildx
            - name: Docker buildx
              uses: docker/setup-buildx-action@v2

# 6. docker login
            - name: Docker login
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

# 7. docker build and push
            - name: Push Image
              uses: docker/build-push-action@v2
              with:
                context: ./
                file: ./Dockerfile
                platforms: 
                push: true
                # DOCKER BUILD -T JSLIM9413/IMAGE/TAGS
                tags: ${{ secrets.DOCKER_USERNAME }}/springapp:${{ github.sha }}

# 파이프라인 작성이 끝나면 로컬 콘솔에서 이미지 빌드, 실행
# docker build ~~~~~
# docker run port(8080:8080) container_name image
